#S3
cloud:
  aws:
    credentials:
      access-key: AKIAWQUOZ3AWGLRAMG5U
      secret-key: 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
    s3:
      bucketName: test-b-class-0000
    region:
      static: ap-northeast-2
  stack:
    auto: false


jwt:
  secret: H7oIaBujRo6fA/a0wdk09iY6STECQZbemMj8bcs5xBMzd0IYxzT+hNQd+fgXvsyz3qHF3DIwuYXUE9m7w5tkDw==